version: '3'
services:
  mongo:
    hostname: mongo
    image: 'mvertes/alpine-mongo:latest'
    volumes:
      - ./mongodb:/data/db
    ports:
      - '27017:27017'
    restart: always
    networks:
      webjet_net:
        ipv4_address: 172.22.240.17
  webjetserver:
    hostname: webjetserver
    image: 'golra03/webjetserver:latest'
    ports:
      - '3001:3001'
    volumes:
      - './logs:/webjet/webjetserver/logs/webjetserver'
    entrypoint:
      - /bin/sh
      - '-c'
      - >-
        set -u
        set -e
        mkdir -p ./logs/webjetserver

        DATE=`date '+%Y-%m-%d_%H-%M-%S'`

        cd /webjet/webjetserver

        npm run start:production
    environment:
      - PORT=3001
      - NODE_ENV=production
      - CINEMAWORLD_HOST=http://172.22.240.12
      - CINEMAWORLD_PORT=3002
      - FILMWORLD_HOST=http://172.22.240.13
      - FILMWORLD_PORT=3003
    restart: always
    networks:
      webjet_net:
        ipv4_address: 172.22.240.11
  cinemaworld:
    hostname: cinemaworld
    image: 'golra03/cinemaworld:latest'
    ports:
      - '3002:3002'
    volumes:
      - './logs:/webjet/cinemaworld/logs/cinemaworld'
    depends_on:
      - mongo
    entrypoint:
      - /bin/sh
      - '-c'
      - >-
        set -u
        set -e
        mkdir -p ./logs/cinemaworld

        DATE=`date '+%Y-%m-%d_%H-%M-%S'`

        cd /webjet/cinemaworld

        npm run start:production
    environment:
      - PORT=3002
      - NODE_ENV=production
      - MONGO_HOST=172.22.240.17
      - MONGO_PORT=27017
      - MONGO_DB=cinemaworld
    restart: always
    networks:
      webjet_net:
        ipv4_address: 172.22.240.12
  filmworld:
    hostname: filmworld
    image: 'golra03/filmworld:latest'
    ports:
      - '3003:3003'
    volumes:
      - './logs:/webjet/filmworld/logs/filmworld'
    depends_on:
      - mongo
    entrypoint:
      - /bin/sh
      - '-c'
      - >-
        set -u
        set -e
        mkdir -p ./logs/filmworld

        DATE=`date '+%Y-%m-%d_%H-%M-%S'`

        cd /webjet/filmworld

        npm run start:production
    environment:
      - PORT=3003
      - NODE_ENV=production
      - MONGO_HOST=172.22.240.17
      - MONGO_PORT=27017
      - MONGO_DB=filmworld
    restart: always
    networks:
      webjet_net:
        ipv4_address: 172.22.240.13
networks:
  webjet_net:
    external: true
